name = "pb"
compatibility_date = "2023-01-28"
compatibility_flags = [ "nodejs_compat" ]

workers_dev = false
main = "src/index.js"

rules = [
  { type = "Text", globs = [ "*/frontend/**", "*/doc/**" ], fallthrough = true }
]

#----------------------------------------
# lines below are what you should modify
#----------------------------------------

[[routes]]
# Refer to https://developers.cloudflare.com/workers/wrangler/configuration/#routes
pattern = "w.730307.xyz"
custom_domain = true

[[kv_namespaces]]
binding = "PB"  # do not touch this
id = "ccd9b27cdd824c298ede6eab06a15e9b"  # id of your KV namespace

[vars]
# must be consistent with your routes
BASE_URL = "https://w.730307.xyz"

# url to repo, displayed in index page
REPO = "https://github.com/SharzyL/pastebin-worker"

# url to favicon
FAVICON = "https://343700.xyz/wp-content/uploads/2023/08/cropped-%E5%A4%B4%E5%83%8F.jpg"

# the name displayed in TOS
TOS_MAINTAINER = "三七"

# the email displayed in TOS
TOS_MAIL = "pb@730307.xyz"

# Cache-Control max-age for static pages
CACHE_STATIC_PAGE_AGE = 7200

# Cache-Control max-age for static pages
CACHE_PASTE_AGE = 600

[vars.BASIC_AUTH]
account = "your_passwd"
